spring.datasource.url=jdbc:postgresql://localhost:5432/prepverse_db
spring.datasource.username=postgres
spring.datasource.password=Shreyash06

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true